name: Fast checkout
description: Uses prebaked repo on self-hosted runners
inputs:
  fetch-depth:
    description: How many commits of history to fetch (0 = all history)
    required: false
    default: 1
    type: number

runs:
  using: composite
  steps:
    - if: ${{ runner.environment != 'self-hosted' && github.event_name != 'pull_request_target' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    # This is necessary to check out the pull request if this run was triggered via a
    # `pull_request_target` event.
    - if: ${{ runner.environment != 'self-hosted' && github.event_name == 'pull_request_target' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ inputs.fetch-depth }}

    # Use prebaked repo on self-hosted runners
    - if: ${{ runner.environment == 'self-hosted' && github.event_name != 'pull_request_target' && inputs.fetch-depth != 0 }}
      shell: bash
      run: git fetch --depth=${{ inputs.fetch-depth }} origin $env:GITHUB_SHA
    - if: ${{ runner.environment == 'self-hosted' && github.event_name != 'pull_request_target' && inputs.fetch-depth == 0 }}
      shell: bash
      run: git fetch origin $env:GITHUB_SHA
    - if: ${{ runner.environment == 'self-hosted' && github.event_name == 'pull_request_target' && inputs.fetch-depth != 0 }}
      shell: bash
      run: git fetch --depth=${{ inputs.fetch-depth }} origin ${{ github.event.pull_request.head.sha }}
    - if: ${{ runner.environment == 'self-hosted' && github.event_name == 'pull_request_target' && inputs.fetch-depth == 0 }}
      shell: bash
      run: git fetch origin ${{ github.event.pull_request.head.sha }}
    - if: ${{ runner.environment == 'self-hosted' }}
      shell: bash
      # Same as `git switch --detach FETCH_HEAD`, but fixes up dirty working
      # trees, in case the runner image was baked with a dirty working tree.
      run: |
        git switch --detach
        git reset --hard FETCH_HEAD
