# IP addresses to listen on, e.g. ::1 for nginx and 192.168.100.1 for libvirt.
listen_on = ["::1", "192.168.100.1"]

# Prepend this to any internal URL in our own responses. Must end with trailing slash.
external_base_url = "https://ci0.servo.org/"

# GitHub Actions runner scope (`/repos/<owner>/<repo>` or `/orgs/<owner>`)
github_api_scope = "/orgs/servo"

# For tokenless runner select, qualified repos must start with this prefix.
allowed_qualified_repo_prefix = "servo/"

# Register runners as “name.0@host”, where “host” is a name identifying this host.
github_api_suffix = "ci0"

# Time to wait before polling for resources again.
monitor_poll_interval = 5

# Time to cache GitHub API responses, to avoid REST API rate limits.
api_cache_timeout = 30

# For tokenless select (POST /select-runner), maximum acceptable age of artifact.
tokenless_select_artifact_max_age = 300

# Maximum time to allow a runner to be StartedOrCrashed.
monitor_start_timeout = 120

# Maximum time to allow a runner to be Reserved.
monitor_reserve_timeout = 60

# Internals: maximum time to wait when sending to the monitor thread.
monitor_thread_send_timeout = 10

# Internals: maximum time to wait when receiving from the monitor thread.
monitor_thread_recv_timeout = 10

# Uncomment to destroy all non-busy runners.
# destroy_all_non_busy_runners = true

# Uncomment to skip GitHub API registration.
# dont_register_runners = true

# Uncomment to avoid creating any runners.
# dont_create_runners = true

# Path to a Servo main repo on the host, to be injected into base images.
main_repo_path = "/root/servo"

# Maximum age of base images before they need to be rebuilt, in seconds.
base_image_max_age = 604800

# How much memory is available for our runners.
available_1g_hugepages = 96
available_normal_memory = "16G"

[profiles.servo-windows10]
profile_name = "servo-windows10"
github_runner_label = "self-hosted-image:windows10"
target_count = 1
requires_1g_hugepages = 24
requires_normal_memory = "1G"  # Arbitrary non-zero guess

[profiles.servo-ubuntu2204]
profile_name = "servo-ubuntu2204"
github_runner_label = "self-hosted-image:ubuntu2204"
target_count = 3
requires_1g_hugepages = 24
requires_normal_memory = "1G"  # Arbitrary non-zero guess

[profiles.servo-macos13]
profile_name = "servo-macos13"
github_runner_label = "self-hosted-image:macos13"
target_count = 0
requires_1g_hugepages = 24
requires_normal_memory = "1G"  # Arbitrary non-zero guess

[profiles.servo-ubuntu2204-wpt]
profile_name = "servo-ubuntu2204-wpt"
github_runner_label = "self-hosted-image:ubuntu2204-wpt"
target_count = 0
requires_1g_hugepages = 24
requires_normal_memory = "1G"  # Arbitrary non-zero guess
