[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.12.1", features = ["with-warp"] }
askama_warp = "0.13.0"
chrono = "0.4.39"
crossbeam-channel = "0.5.13"
dotenv = "0.15.0"
http = "0.2"
itertools = "0.13.0"
jane-eyre = "0.3.0"
mktemp = "0.5.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
subprocess = "0.2.9"
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.15"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
warp = "0.3.7"
