[package]
name = "settings"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = { workspace = true }
jane-eyre = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
